# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 03:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.IntegerField(default=0)),
                ('fullname', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('sexo', models.CharField(max_length=1)),
                ('telefono', models.CharField(max_length=200)),
                ('movil', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField()),
                ('profesion', models.CharField(max_length=200)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField(max_length=40)),
                ('status', models.IntegerField(default=1)),
                ('id_dispositivo', models.CharField(max_length=200)),
                ('latitud', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=7, max_digits=10)),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='DireccionCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(default='Venezuela', max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DireccionClientes', related_query_name='DireccionCliente', to='perfiles.Cliente')),
            ],
            options={
                'db_table': 'direccion_cliente',
            },
        ),
        migrations.CreateModel(
            name='RechazaClausula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentarios', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('contactado', models.IntegerField(default=0)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RechazaClausulas', related_query_name='RechazaClausula', to='perfiles.Cliente')),
            ],
            options={
                'db_table': 'rechaza_clausula',
            },
        ),
    ]
