# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 03:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customs', '0001_initial'),
        ('perfiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodbarraArticulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barra', models.CharField(max_length=30)),
                ('categoria', models.CharField(max_length=200)),
                ('marca', models.CharField(max_length=200)),
                ('observacion', models.CharField(max_length=200)),
                ('status', models.IntegerField(default=1)),
                ('id_articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customs.Articulo')),
            ],
            options={
                'db_table': 'codbarra_articulos',
            },
        ),
        migrations.CreateModel(
            name='OrdenServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descuento', models.IntegerField(default=0)),
                ('precio_orden', models.FloatField()),
                ('cantidad_piezas', models.IntegerField(default=0)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateTimeField(null=True)),
                ('recepcion', models.CharField(max_length=200)),
                ('forma_entrega', models.CharField(max_length=200)),
                ('observacion', models.CharField(max_length=200)),
                ('status', models.IntegerField(default=1)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrdenServicio', related_query_name='OrdenServicio', to='perfiles.Cliente')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrdenServicio', related_query_name='OrdenServicio', to='customs.Empresa')),
                ('id_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrdenServicio', related_query_name='OrdenServicio', to='customs.Servicio')),
            ],
            options={
                'db_table': 'orden_servicios',
            },
        ),
        migrations.AddField(
            model_name='codbarraarticulo',
            name='id_orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.OrdenServicio'),
        ),
        migrations.AlterUniqueTogether(
            name='codbarraarticulo',
            unique_together=set([('id_articulo', 'id_orden', 'codigo_barra')]),
        ),
    ]
