# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 03:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codbarraarticulo',
            name='id_articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Articulo', related_query_name='Articulo', to='customs.Articulo'),
        ),
        migrations.AlterField(
            model_name='codbarraarticulo',
            name='id_orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrdenServicio', related_query_name='OrdenServicio', to='ordenes.OrdenServicio'),
        ),
        migrations.AlterField(
            model_name='ordenservicio',
            name='id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cliente', related_query_name='Cliente', to='perfiles.Cliente'),
        ),
        migrations.AlterField(
            model_name='ordenservicio',
            name='id_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Empresa', related_query_name='Empresa', to='customs.Empresa'),
        ),
    ]
